// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/business/business.proto

/*
Package me_moye_srv_business is a generated protocol buffer package.

It is generated from these files:
	proto/business/business.proto

It has these top-level messages:
	Message
	Request
	Response
	StreamingRequest
	StreamingResponse
	Ping
	Pong
*/
package me_moye_srv_business

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for API service

type APIService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (API_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (API_PingPongService, error)
}

type aPIService struct {
	c    client.Client
	name string
}

func NewAPIService(name string, c client.Client) APIService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "me.moye.srv.business"
	}
	return &aPIService{
		c:    c,
		name: name,
	}
}

func (c *aPIService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "API.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (API_StreamService, error) {
	req := c.c.NewRequest(c.name, "API.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &aPIServiceStream{stream}, nil
}

type API_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type aPIServiceStream struct {
	stream client.Stream
}

func (x *aPIServiceStream) Close() error {
	return x.stream.Close()
}

func (x *aPIServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *aPIServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *aPIServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIService) PingPong(ctx context.Context, opts ...client.CallOption) (API_PingPongService, error) {
	req := c.c.NewRequest(c.name, "API.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &aPIServicePingPong{stream}, nil
}

type API_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type aPIServicePingPong struct {
	stream client.Stream
}

func (x *aPIServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *aPIServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *aPIServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *aPIServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *aPIServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for API service

type APIHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, API_StreamStream) error
	PingPong(context.Context, API_PingPongStream) error
}

func RegisterAPIHandler(s server.Server, hdlr APIHandler, opts ...server.HandlerOption) error {
	type aPI interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type API struct {
		aPI
	}
	h := &aPIHandler{hdlr}
	return s.Handle(s.NewHandler(&API{h}, opts...))
}

type aPIHandler struct {
	APIHandler
}

func (h *aPIHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.APIHandler.Call(ctx, in, out)
}

func (h *aPIHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.APIHandler.Stream(ctx, m, &aPIStreamStream{stream})
}

type API_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type aPIStreamStream struct {
	stream server.Stream
}

func (x *aPIStreamStream) Close() error {
	return x.stream.Close()
}

func (x *aPIStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *aPIStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *aPIStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *aPIHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.APIHandler.PingPong(ctx, &aPIPingPongStream{stream})
}

type API_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type aPIPingPongStream struct {
	stream server.Stream
}

func (x *aPIPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *aPIPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *aPIPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *aPIPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *aPIPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
